# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "**/typestubs/*.pyi" # do not lint typestubs
]

include = [
    "src/**/*.py",
    "tests/**/*.py",
]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    # "W", # pycodestyle warnings
    "D",  # pycodestyle
    "A",  # prevent using keywords that clobber python builtins
    "B",  # bugbear: security warnings
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP",  # alert you when better syntax is available in your python version
]

ignore = [
    "D104", # Missing docstring in public package
    "D100", # Missing docstring in public module
    "D105", # Missing docstring in magic method
    "E252", # Missing spaces around equal sign in kwargs
    "D101", # 
    "D102", # 
    "D103", # 
    "D107", #
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
pydocstyle.convention = "google"
task-tags = ["TODO", "NOTE"]

[lint.pycodestyle]
max-line-length = 100
max-doc-length = 120
ignore-overlong-task-comments = true

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Do not format typestubs, as generally auto-generated (e.g by PyRight)
exclude = ["*.pyi"]